name: Example of cURL action

on: 
  push:
    branches: [ "main" ]
jobs:
  test-curl-action:
    name: "Send App in Production"
    runs-on: ubuntu-latest
    steps:
      - name: "Call API"
        uses: indiesdev/curl@v1.1
        with:
          url: https://api.heroku.com/pipeline-promotions
          method: "POST"
          accept: 201
          headers: '{ "Accept": "application/vnd.heroku+json; version=3", "Content-Type": "application/json; charset=utf-8"}'
          body: '{"pipeline":{"id":"25d6b52e-ad5b-424a-832d-69b13d6481c1"},"source":{"app":{"id":"fb33ce03-1971-45f0-8829-83a431a9b53a"}},"targets":[{"app":{"id":"6931d598-a4ee-41c5-9105-b24e03d5ac6e"}}]}'

          timeout: 5000


          # The authentication using token
          # This will override the Authorization header, for example Authorization: Bearer QWxhZGRpbjpPcGVuU2VzYW1l
          bearer-token: ${{ secrets.BEARER_TOKEN_HEROKU_PRODUCTION }}



