name: System Testing

on:
  pull_request:
    branches: [ "release" ]


jobs:
  system-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          branch: release
          heroku_api_key: ${{HEROKU_API_KEY}}
          heroku_app_name: "meileafapp"
          heroku_email: "basil.peter@hotmail.ch"
          
      - uses: matt-ball/newman-action@master
        with:
          collection: src/test/java/com/example/jwt/domain/order/system/MeileafTests.postman_collection.json
          envVar: '[{"key": "API_URL", "value": "https://meileafapp.herokuapp.com"}]'


 
